# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bucket}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tylerkovacs"]
  s.date = %q{2010-07-11}
  s.description = %q{See README}
  s.email = %q{tyler.kovacs@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION.yml",
     "bucket.gemspec",
     "lib/bucket.rb",
     "lib/bucket/base.rb",
     "lib/bucket/frameworks/rails.rb",
     "lib/bucket/frameworks/rails/filters.rb",
     "lib/bucket/frameworks/rails/helpers.rb",
     "lib/bucket/test.rb",
     "spec/lib/bucket_test_spec.rb",
     "spec/lib/frameworks/rails/filters_spec.rb",
     "spec/lib/frameworks/rails/helpers_spec.rb",
     "spec/lib/frameworks/rails/rails_spec_helper.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tylerkovacs/bucket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A/B testing.}
  s.test_files = [
    "spec/lib/bucket_test_spec.rb",
     "spec/lib/frameworks/rails/filters_spec.rb",
     "spec/lib/frameworks/rails/rails_spec_helper.rb",
     "spec/lib/frameworks/rails/helpers_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
